apiVersion: v1
kind: Pod
metadata:
  name: gis
  labels:
    app: gis
spec:
  containers:
  - name: gis
    image: modularniurad/gis
    imagePullPolicy: Never
    env:
    - name: DATABASE_URL
      value: postgres://gandalf:hovno@postgre-service/gis
    - name: HOST
      value: 0.0.0.0